name: Test PR

on:
  pull_request:
    types: [ opened, synchronize ]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Bench
        run: cargo test --all
